{{- if .Values.serviceAccount.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "job-dispatcher.fullname" . }}-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "job-dispatcher.fullname" . }}-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "job-dispatcher.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "job-dispatcher.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
